### ISSUE TITLE
The use of http in font import causes chrome to block them when redmine is served under https

### ISSUE THREAD

**Issue by kragacles** [themondays/redpenny#3]
**Cause**

Line 11 in stylesheets/application.css uses http when loading fonts.googleapis.com:
`@import "http://fonts.googleapis.com/css?family=PT+Sans:400,700|Source+Code+Pro";`

**Fix**

Simply changing to https removes the issue:
`@import "https://fonts.googleapis.com/css?family=PT+Sans:400,700|Source+Code+Pro";`

**Comment by themondays** [comment]
Thanks will update.
